=== PavelClaudiuStefan/FMI/An_3_Semestru_1/DezvoltareAplicatiiWebC#/Cursuri/Lecture8/fsynsets.dtd
<?xml version="1.0" encoding="iso-8859-1"?>
<!ELEMENT FSynsetsDoc (synset)+>
<!ATTLIST FSynsetsDoc pos CDATA #REQUIRED>
<!ELEMENT synset (synset_en, e-sets?, fsynsets)>
<!ATTLIST synset offset CDATA #REQUIRED>
<!ELEMENT synset_en (gloss, word+)>
<!ELEMENT e-sets (e-set)+>
<!ELEMENT e-set (eword, word+)>
<!ATTLIST e-set score CDATA #REQUIRED>
<!ELEMENT fsynsets (fsynset)*>
<!ELEMENT fsynset (word)+>
<!ELEMENT word (#PCDATA)>
<!ELEMENT eword (#PCDATA)>
<!ELEMENT gloss (#PCDATA)>

=== PavelClaudiuStefan/FMI/An_3_Semestru_1/DezvoltareAplicatiiWEB/Cursuri/Lecture8/fsynsets_n_ro.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE FSynsetsDoc SYSTEM "fsynsets.dtd">

<FSynsetsDoc pos="noun">
   <synset offset="4123">
      <synset_en>
         <gloss>a human being; "there was too much for one person to do"</gloss>
         <word>person</word>
         <word>individual</word>
         <word>someone</word>
         <word>somebody</word>
         <word>mortal</word>
         <word>human</word>
         <word>soul</word>
      </synset_en>
      <e-sets>
         <e-set score="3.0">
            <eword>person</eword>
            <word>persoana</word>
            <word>individ</word>
            <word>ins</word>
         </e-set>
         <e-set score="3.0">
            <eword>person</eword>
            <word>persoana</word>
         </e-set>
         <e-set score="3.0">
            <eword>individual</eword>
            <word>persoana</word>
            <word>individ</word>
         </e-set>
         <e-set score="3.0">
            <eword>someone</eword>
            <word>cineva</word>
         </e-set>
         <e-set score="3.0">
            <eword>somebody</eword>
            <word>cineva</word>
         </e-set>
         <e-set score="3.0">
            <eword>soul</eword>
            <word>suflet</word>
         </e-set>
         <e-set score="2.0">
            <eword>human</eword>
            <word>muritor</word>
         </e-set>
         <e-set score="1.0">
            <eword>mortal</eword>
            <word>muritor</word>
         </e-set>
      </e-sets>
      <fsynsets>
         <fsynset>
            <word>persoana</word>
            <word>individ</word>
            <word>ins</word>
            <word>cineva</word>
            <word>muritor</word>
            <word>suflet</word>
         </fsynset>
         <fsynset>
            <word>persoana</word>
            <word>individ</word>
            <word>cineva</word>
            <word>muritor</word>
            <word>suflet</word>
         </fsynset>
      </fsynsets>
   </synset>
   <synset offset="10572">
      <synset_en>
         <gloss>that which has mass and occupies space; "an atom is the smallest indivisible unit of matter"</gloss>
         <word>substance</word>
         <word>matter</word>
      </synset_en>
      <e-sets>
         <e-set score="3.0">
            <eword>substance</eword>
            <word>materie</word>
            <word>substanta</word>
         </e-set>
         <e-set score="3.0">
            <eword>matter</eword>
            <word>materie</word>
            <word>substanta</word>
         </e-set>
         <e-set score="3.0">
            <eword>matter</eword>
            <word>fond</word>
         </e-set>
         <e-set score="2.0">
            <eword>substance</eword>
            <word>esenta</word>
            <word>fond</word>
         </e-set>
         <e-set score="1.0">
            <eword>matter</eword>
            <word>chestiune</word>
            <word>problema</word>
         </e-set>
         <e-set score="1.0">
            <eword>matter</eword>
            <word>lucru</word>
            <word>fapt</word>
            <word>obiect</word>
         </e-set>
         <e-set score="1.0">
            <eword>matter</eword>
            <word>subiect</word>
         </e-set>
      </e-sets>
      <fsynsets>
         <fsynset>
            <word>materie</word>
            <word>substanta</word>
         </fsynset>
         <fsynset>
            <word>materie</word>
            <word>substanta</word>
            <word>fond</word>
         </fsynset>
      </fsynsets>
   </synset>
   <synset offset="17487">
      <synset_en>
         <gloss>something that people do or cause to happen</gloss>
         <word>act</word>
      </synset_en>
      <e-sets>
         <e-set score="0.5">
            <eword>act</eword>
            <word>fapta</word>
            <word>fapt</word>
            <word>act</word>
            <word>actiune</word>
         </e-set>
         <e-set score="0.33333334">
            <eword>act</eword>
            <word>act</word>
            <word>titlu</word>
            <word>document</word>
         </e-set>
         <e-set score="0.16666667">
            <eword>act</eword>
            <word>act</word>
            <word>lege</word>
            <word>edict</word>
            <word>decret</word>
            <word>hotarare</word>
            <word>rezolutie</word>
         </e-set>
      </e-sets>
      <fsynsets>
         <fsynset>
            <word>fapta</word>
            <word>fapt</word>
            <word>act</word>
            <word>actiune</word>
         </fsynset>
      </fsynsets>
   </synset>
   <synset offset="18916">
      <synset_en>
         <gloss>an abstraction belonging to or characteristic of two entities or parts together</gloss>
         <word>relation</word>
      </synset_en>
      <e-sets>
         <e-set score="1.0">
            <eword>relation</eword>
            <word>relatie</word>
         </e-set>
         <e-set score="1.0">
            <eword>relation</eword>
            <word>raport</word>
            <word>legatura</word>
         </e-set>
         <e-set score="1.0">
            <eword>relation</eword>
            <word>ruda</word>
            <word>rubedenie</word>
            <word>neam</word>
         </e-set>
      </e-sets>
      <fsynsets>
         <fsynset>
            <word>relatie</word>
         </fsynset>
         <fsynset>
            <word>raport</word>
            <word>legatura</word>
         </fsynset>
         <fsynset>
            <word>ruda</word>
            <word>rubedenie</word>
            <word>neam</word>
         </fsynset>
      </fsynsets>
   </synset>
   <synset offset="24107">
      <synset_en>
         <gloss>(usually plural) mutual dealings or connections among persons or groups: "international relations"</gloss>
         <word>relation</word>
      </synset_en>
      <e-sets>
         <e-set score="1.0">
            <eword>relation</eword>
            <word>relatie</word>
         </e-set>
         <e-set score="1.0">
            <eword>relation</eword>
            <word>raport</word>
            <word>legatura</word>
         </e-set>
         <e-set score="1.0">
            <eword>relation</eword>
            <word>ruda</word>
            <word>rubedenie</word>
            <word>neam</word>
         </e-set>
      </e-sets>
      <fsynsets>
         <fsynset>
            <word>relatie</word>
         </fsynset>
         <fsynset>
            <word>raport</word>
            <word>legatura</word>
         </fsynset>
         <fsynset>
            <word>ruda</word>
            <word>rubedenie</word>
            <word>neam</word>
         </fsynset>
      </fsynsets>
   </synset>
   <synset offset="133315">
      <synset_en>
         <gloss>the act of rejecting something; "his proposals were met with rejection"</gloss>
         <word>rejection</word>
      </synset_en>
      <e-sets>
         <e-set score="1.0">
            <eword>rejection</eword>
            <word>respingere</word>
         </e-set>
         <e-set score="1.0">
            <eword>rejection</eword>
            <word>rebutare</word>
         </e-set>
      </e-sets>
      <fsynsets>
         <fsynset>
            <word>respingere</word>
         </fsynset>
         <fsynset>
            <word>rebutare</word>
         </fsynset>
      </fsynsets>
   </synset>
   <synset offset="135310">
      <synset_en>
         <gloss>a group's refusal to have commercial dealings with some organization in protest against its policies</gloss>
         <word>boycott</word>
      </synset_en>
      <e-sets>
         <e-set score="0.5">
            <eword>boycott</eword>
            <word>boicot</word>
            <word>boicotare</word>
         </e-set>
      </e-sets>
      <fsynsets>
         <fsynset>
            <word>boicot</word>
            <word>boicotare</word>
         </fsynset>
      </fsynsets>
   </synset>
   <synset offset="135464">
      <synset_en>
         <gloss>the act of banishing someone</gloss>
         <word>banishment</word>
         <word>proscription</word>
      </synset_en>
      <e-sets>
         <e-set score="2.0">
            <eword>proscription</eword>
            <word>surghiunire</word>
            <word>exilare</word>
         </e-set>
         <e-set score="0.8333333">
            <eword>banishment</eword>
            <word>exilare</word>
            <word>surghiunire</word>
            <word>exil</word>
            <word>surghiun</word>
            <word>expulzare</word>
            <word>ostracizare</word>
         </e-set>
      </e-sets>
      <fsynsets>
         <fsynset>
            <word>exilare</word>
            <word>surghiunire</word>
            <word>exil</word>
            <word>surghiun</word>
            <word>expulzare</word>
            <word>ostracizare</word>
         </fsynset>
      </fsynsets>
   </synset>
   <synset offset="135765">
      <synset_en>
         <gloss>the act of expelling someone</gloss>
         <word>ejection</word>
         <word>exclusion</word>
         <word>expulsion</word>
         <word>riddance</word>
      </synset_en>
      <e-sets>
         <e-set score="1.0">
            <eword>exclusion</eword>
            <word>excludere</word>
         </e-set>
         <e-set score="0.8">
            <eword>expulsion</eword>
            <word>expulzare</word>
            <word>alungare</word>
            <word>izgonire</word>
            <word>eliminare</word>
            <word>exmatriculare</word>
         </e-set>
         <e-set score="0.5">
            <eword>riddance</eword>
            <word>scapare</word>
            <word>descotorosire</word>
         </e-set>
      </e-sets>
      <fsynsets>
         <fsynset>
            <word>excludere</word>
            <word>expulzare</word>
            <word>alungare</word>
            <word>izgonire</word>
            <word>eliminare</word>
            <word>exmatriculare</word>
            <word>scapare</word>
            <word>descotorosire</word>
